### ISSUE TITLE
improve nomenclature consistency

### ISSUE THREAD

**Issue by AndreaSanchezTapia** [GlobalFishingWatch/gfwr#146]
**Vessel ID**
Vessel IDs, vessel IDs, vesselID (in the table), and VesselID (in the documentation) are spelled in many ways in different places.
- the parameters are _called_ as `id` in `get_vessel_info()` and `vessels` in other functions
- they're named `id` or `vesselId` in the API results (`selReportedInfo$id`, `combinedSourcesInfo$VesselID` but there are other fields named `id` in the returning datasets that are not vessel IDs like `registryInfo$id`

Possible discussion with the API team as well to avoid solving downstream.

**Comment by AndreaSanchezTapia** [comment]
The tinyest change to avoid a long explanation is renaming `selfReportedInfo$id` to `selfReportedInfo$vesselId` in the results. No change to parameters or API calls, only readme and vignette results processing.

**Comment by AndreaSanchezTapia** [comment]
readd the explanation that ssvid is MMSI in the case of AIS

**Comment by jflowernet** [comment]
Hi. Hope you don't mind me jumping in, but I had a thought about argument naming! I notice in the latest version of `gfwr`, `get_raster()` has had some changes, one of which is that the user specified `region` should be an `sf` object (great enhancement, thanks!). Given this change, wouldn't it make sense to use `region_source = "user_polygon"`, or something similar, rather than `"user_json"`?

**Comment by AndreaSanchezTapia** [comment]
Thanks for flagging this, @jflowernet ! I made a correction to `USER_SHAPEFILE`.

**Comment by AndreaSanchezTapia** [comment]
- [ ] `id` in `get_event()` should be named `eventID`
- [ ] `id` in `get_vessel_info$registryInfo` should be named `registryId`

**Comment by AndreaSanchezTapia** [comment]
Closing for now but other changes may be necessary.
